### ISSUE TITLE
get OpenAI answers to questions

### ISSUE THREAD

**Issue by bbest** [cstories-app/scripts#1]
See:
* [OpenAI's latest GPT-3 model generates better and longer texts](https://the-decoder.com/openais-latest-gpt-3-model-generates-better-and-longer-texts/)
* [Playground - OpenAI API](https://beta.openai.com/playground?model=text-davinci-003)

**Comment by bbest** [comment]
- [scripts/openai.html](https://cstories.app/scripts/openai.html)
  Initial test of using the [openai](https://irudnyts.github.io/openai/) R package, which doesn't match or take advantage of many features visible in [playground](https://beta.openai.com/playground), so probably need to write our own httr2 interface, similar to [scripts/news-api.html](https://cstories.app/scripts/news-api.html). This initial request seems to have cost $0.00308, so ~$3 for every 1,000 requests.

**Comment by bbest** [comment]
* [Overview - OpenAI API](https://beta.openai.com/overview)
  * [Quickstart tutorial - OpenAI API](https://beta.openai.com/docs/quickstart/build-your-application)
  * [Examples](https://beta.openai.com/examples)
    * [Q& A Example](https://beta.openai.com/examples/default-qa)
* [Aligning Language Models to Follow Instructions](https://openai.com/blog/instruction-following/)
* [Factual Responses, Text completion | OpenAI API](https://beta.openai.com/docs/guides/completion/factual-responses)
* [API Reference - OpenAI API](https://beta.openai.com/docs/api-reference/introduction) with official Python module:
  ```bash
  pip install openai
  ```

**Comment by bbest** [comment]
* [API Reference - OpenAI API](https://beta.openai.com/docs/api-reference/authentication)
  Example with the openai Node.js package:
  ```js
  import { Configuration, OpenAIApi } from "openai";
  const configuration = new Configuration({
      organization: "org-CF3k6MCgP7TknPgk3sUfx2fP",
      apiKey: process.env.OPENAI_API_KEY,
  });
  const openai = new OpenAIApi(configuration);
  const response = await openai.listEngines();
  ```
* [How to read environment variables from Node.js](https://nodejs.dev/en/learn/how-to-read-environment-variables-from-nodejs/)
  setting `process.env`
* [How to Create a Basic Chatbot in JavaScript | HTMLGoodies.com](https://www.htmlgoodies.com/javascript/basic-chatbot-in-javascript/)
* [How to Make a Chatbot Using JS](https://stormotion.io/blog/how-to-make-a-chatbot-using-js/)

**Comment by bbest** [comment]
[how to create a chatbot with openai on my website - Google Search](https://www.google.com/search?q=how+to+create+a+chatbot+with+openai+on+my+website&oq=how+to+create+a+chatbot+with+openai+on+my+website&aqs=chrome..69i57.15699j0j7&sourceid=chrome&ie=UTF-8):
* [Building a Chatbot with OpenAI's GPT-3 engine, Twilio SMS and Python](https://www.twilio.com/blog/openai-gpt-3-chatbot-python-twilio-sms)
* [Build custom-informed GPT-3-based chatbots for your website with very simple code | by LucianoSphere | Towards Data Science](https://towardsdatascience.com/custom-informed-gpt-3-models-for-your-website-with-very-simple-code-47134b25620b)
* [How To Build a GPT-3 Chatbot with Python | by John Mannelly | Medium](https://jman4190.medium.com/how-to-build-a-gpt-3-chatbot-with-python-7b83e55805e6)
* [ChatGPT: how to use this viral, often hilarious AI chatbot | Digital Trends](https://www.digitaltrends.com/computing/how-to-use-openai-chatgpt-text-generation-chatbot/)

**Comment by geocoug** [comment]
Also check out [ChatGPT](https://chat.openai.com/chat).

**Comment by bbest** [comment]
Hi @geocoug, I got a basic bot working here:

https://cstories.app/chat/
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/2837257/207430411-803698b7-a5f7-41e6-8eeb-572fd6526ad6.png">

Used code from [How to Create a Basic Chatbot in JavaScript | HTMLGoodies.com](https://www.htmlgoodies.com/javascript/basic-chatbot-in-javascript/).

Next steps:
- [x] setup API in new repo [api](https://github.com/cstories-app/api)
- [x] test API with chat bot to localhost
- [ ] setup server with API and update chat bot
- [ ] move chat bot to front page with a banner

Note: I asked a CTO friend about securing the API away from non-website clients and he said there isn't a way to do that, nor is it usually much of a concern, but that we could do things like throttle # of requests per hour and/or require authentication after a certain number of requests.

**Comment by bbest** [comment]
PS For now, this chat bot only shows `answers` from pre-canned questions, ie `utterances`, otherwise shows one of the  `alternatives`, all hard coded as arrays in the [chat.js](https://github.com/cstories-app/cstories-app.github.io/blob/57f1608b3a270a94d65e1e7a16ed950b459cc2f9/chat/chat.js#L84-L116).

**Comment by bbest** [comment]
## Fine Tune and Engineer Prompts

* [openai-cookbook/Question\_answering\_using\_embeddings.ipynb at main · openai/openai-cookbook](https://github.com/openai/openai-cookbook/blob/main/examples/Question_answering_using_embeddings.ipynb)
  * eg "Preventing hallucination with prompt engineering"
* [Text completion - OpenAI API](https://beta.openai.com/docs/guides/completion/introduction)
* [models - API Reference - OpenAI API](https://beta.openai.com/docs/api-reference/models)
* [fine-tunes - API Reference - OpenAI API](https://beta.openai.com/docs/api-reference/fine-tunes/create)
* [moderations - API Reference - OpenAI API](https://beta.openai.com/docs/api-reference/moderations/create)
* [parameter-details - API Reference - OpenAI API](https://beta.openai.com/docs/api-reference/parameter-details)
* [Playground - OpenAI API](https://beta.openai.com/playground)

**Comment by bbest** [comment]
Got API working on localhost with https://github.com/cstories-app/api/commit/cbd49272e665b3052df5feddc0b7a2a67bd87a49:

http://127.0.0.1:8000/

<img width="1395" alt="Screen Shot 2022-12-13 at 12 43 08 PM" src="https://user-images.githubusercontent.com/2837257/207439729-af70d00e-e245-4749-9bda-b827ca3e2794.png">
<img width="1386" alt="Screen Shot 2022-12-13 at 12 43 31 PM" src="https://user-images.githubusercontent.com/2837257/207439773-4d19b0a2-9a04-4256-b88d-e33ecf7b4da5.png">

**Comment by bbest** [comment]
@geocoug, can you please see about lining up:

- [x] a basic **server** to run the API, to eventual log, filter, refine and throttle questions and responses?
- [x] OpenAI account with Integral, min $120

**Comment by bbest** [comment]
Ok, the web chat/ (with branch [chat-to-api](https://github.com/cstories-app/cstories-app.github.io/tree/a6b387c791bf5b6bcddd633b3b3056aaeb4526f3) is now working with the local API.

<img width="826" alt="image" src="https://user-images.githubusercontent.com/2837257/207461230-ec54abbc-dc77-4074-a3b1-46f21c0d6f2a.png">

**Comment by geocoug** [comment]
@bbest - see updated README via [b079334](https://github.com/cstories-app/api/commit/b0793343b8b5480bf803e71c1d8972744a6f3663) for server info. OpenAI key can be found at /share/github/api/.env.
